// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEG.DataAccess;

#nullable disable

namespace SEG.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719192248_SEG_Inicial")]
    partial class SEG_Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.ToTable("SEG_Acciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2323),
                            Nombre = "CONSULTAR",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2326),
                            Nombre = "CREAR",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2328),
                            Nombre = "MODIFICAR",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2330),
                            Nombre = "ELIMINAR",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2332),
                            Nombre = "LISTAR",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "CREARCONSEDE",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2333),
                            Nombre = "CREAR CON SEDE",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "CREARCONGRUPO",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2336),
                            Nombre = "CREAR CON GRUPO",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_ColaSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("Text")
                        .HasComment("Detalle de error de procasado de la solicitud.");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasComment("Estado del proceso de la solicitud. (0: Pendiente, 1: Procesando, 2: Exitosa, 3: Fallida).");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("datetime");

                    b.Property<int>("Intentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("Intentos del proceso");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("Text")
                        .HasComment("Payload para la solicitud.");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Tipo de solicitud a realizar.");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasComment("Url destino para la cual se publica el evento.");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("Tipo");

                    b.ToTable("SEG_ColaSolicitudes");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.ToTable("SEG_Grupos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "ADMINISTRADORSISTEMA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2239),
                            Nombre = "ADMINISTRADOR SISTEMA",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "ADMINISTRADOREMPRESA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2241),
                            Nombre = "ADMINISTRADOR DE EMPRESA",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "ADMINISTRADORSEDE",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2242),
                            Nombre = "ADMINISTRADOR DE SEDE",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "CONTRARREFERENCIA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2244),
                            Nombre = "USUARIOS DE CONTRARREFERENCIA",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "REFERENCIA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2246),
                            Nombre = "USUARIOS DE REFERENCIA",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "REFERENCIAYCONTRARREFERENCIA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2248),
                            Nombre = "USUARIOS DE REFERENCIA Y CONTRARREFERENCIA",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_GrupoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.HasIndex("GrupoId", "PermisoId")
                        .IsUnique();

                    b.ToTable("SEG_GruposPermisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2525),
                            GrupoId = 1,
                            PermisoId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2526),
                            GrupoId = 1,
                            PermisoId = 2,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2528),
                            GrupoId = 1,
                            PermisoId = 3,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2529),
                            GrupoId = 1,
                            PermisoId = 4,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2531),
                            GrupoId = 1,
                            PermisoId = 5,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2532),
                            GrupoId = 1,
                            PermisoId = 6,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2533),
                            GrupoId = 1,
                            PermisoId = 7,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2535),
                            GrupoId = 1,
                            PermisoId = 8,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 9,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2536),
                            GrupoId = 1,
                            PermisoId = 9,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 10,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2538),
                            GrupoId = 1,
                            PermisoId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 11,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2539),
                            GrupoId = 1,
                            PermisoId = 11,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 12,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2540),
                            GrupoId = 1,
                            PermisoId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 13,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2542),
                            GrupoId = 1,
                            PermisoId = 13,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 14,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2543),
                            GrupoId = 1,
                            PermisoId = 14,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 15,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2544),
                            GrupoId = 1,
                            PermisoId = 15,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 16,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2546),
                            GrupoId = 1,
                            PermisoId = 16,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 17,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2549),
                            GrupoId = 1,
                            PermisoId = 17,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 18,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2550),
                            GrupoId = 1,
                            PermisoId = 18,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 19,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2552),
                            GrupoId = 1,
                            PermisoId = 19,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 20,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2553),
                            GrupoId = 1,
                            PermisoId = 20,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 21,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2554),
                            GrupoId = 1,
                            PermisoId = 21,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 22,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2556),
                            GrupoId = 1,
                            PermisoId = 22,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 23,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2557),
                            GrupoId = 1,
                            PermisoId = 23,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 24,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2558),
                            GrupoId = 1,
                            PermisoId = 24,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 25,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2559),
                            GrupoId = 1,
                            PermisoId = 25,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 26,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2561),
                            GrupoId = 1,
                            PermisoId = 26,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 27,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2562),
                            GrupoId = 1,
                            PermisoId = 27,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 28,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2564),
                            GrupoId = 1,
                            PermisoId = 28,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 29,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2566),
                            GrupoId = 1,
                            PermisoId = 29,
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasComment("Código único del permiso.");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasComment("Nombre descriptivo del permiso.");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.HasIndex("ProgramaId", "AccionId")
                        .IsUnique();

                    b.ToTable("SEG_Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccionId = 1,
                            Codigo = "GRUPOS.CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2411),
                            Nombre = "CONSULTAR GRUPOS",
                            ProgramaId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccionId = 2,
                            Codigo = "GRUPOS.CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2414),
                            Nombre = "CREAR GRUPOS",
                            ProgramaId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccionId = 3,
                            Codigo = "GRUPOS.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2416),
                            Nombre = "MODIFICAR GRUPOS",
                            ProgramaId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            AccionId = 4,
                            Codigo = "GRUPOS.ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2418),
                            Nombre = "ELIMINAR GRUPOS",
                            ProgramaId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            AccionId = 5,
                            Codigo = "GRUPOS.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2420),
                            Nombre = "LISTAR GRUPOS",
                            ProgramaId = 1,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            AccionId = 1,
                            Codigo = "PROGRAMAS.CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2421),
                            Nombre = "CONSULTAR PROGRAMAS",
                            ProgramaId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            AccionId = 2,
                            Codigo = "PROGRAMAS.CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2423),
                            Nombre = "CREAR PROGRAMAS",
                            ProgramaId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            AccionId = 3,
                            Codigo = "PROGRAMAS.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2425),
                            Nombre = "MODIFICAR PROGRAMAS",
                            ProgramaId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 9,
                            AccionId = 4,
                            Codigo = "PROGRAMAS.ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2426),
                            Nombre = "ELIMINAR PROGRAMAS",
                            ProgramaId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 10,
                            AccionId = 5,
                            Codigo = "PROGRAMAS.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2428),
                            Nombre = "LISTAR PROGRAMAS",
                            ProgramaId = 10,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 11,
                            AccionId = 6,
                            Codigo = "USUARIOS.CREARCONSEDE",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2430),
                            Nombre = "CREAR USUARIOS CON SEDE",
                            ProgramaId = 11,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 12,
                            AccionId = 7,
                            Codigo = "USUARIOS.CREARCONGRUPO",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2431),
                            Nombre = "CREAR USUARIOS CON GRUPO",
                            ProgramaId = 11,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 13,
                            AccionId = 1,
                            Codigo = "USUARIOS.CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2433),
                            Nombre = "CONSULTAR USUARIOS",
                            ProgramaId = 11,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 14,
                            AccionId = 5,
                            Codigo = "USUARIOS.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2435),
                            Nombre = "LISTAR USUARIOS",
                            ProgramaId = 11,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 15,
                            AccionId = 2,
                            Codigo = "USUARIOSSEDESGRUPOS.CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2436),
                            Nombre = "CREAR USUARIOS SEDES GRUPOS",
                            ProgramaId = 9,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 16,
                            AccionId = 3,
                            Codigo = "USUARIOSSEDESGRUPOS.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2438),
                            Nombre = "MODIFICAR USUARIOS SEDES GRUPOS",
                            ProgramaId = 9,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 17,
                            AccionId = 4,
                            Codigo = "USUARIOSSEDESGRUPOS.ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2440),
                            Nombre = "ELIMINAR USUARIOS SEDES GRUPOS",
                            ProgramaId = 9,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 18,
                            AccionId = 1,
                            Codigo = "ACCIONES.CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2441),
                            Nombre = "CONSULTAR ACCIONES",
                            ProgramaId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 19,
                            AccionId = 2,
                            Codigo = "ACCIONES.CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2443),
                            Nombre = "CREAR ACCIONES",
                            ProgramaId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 20,
                            AccionId = 3,
                            Codigo = "ACCIONES.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2445),
                            Nombre = "MODIFICAR ACCIONES",
                            ProgramaId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 21,
                            AccionId = 4,
                            Codigo = "ACCIONES.ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2446),
                            Nombre = "ELIMINAR ACCIONES",
                            ProgramaId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 22,
                            AccionId = 5,
                            Codigo = "ACCIONES.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2448),
                            Nombre = "LISTAR ACCIONES",
                            ProgramaId = 12,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 23,
                            AccionId = 3,
                            Codigo = "PERMISOS.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2450),
                            Nombre = "MODIFICAR PERMISOS",
                            ProgramaId = 13,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 24,
                            AccionId = 5,
                            Codigo = "PERMISOS.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2451),
                            Nombre = "LISTAR PERMISOS",
                            ProgramaId = 13,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 25,
                            AccionId = 1,
                            Codigo = "GRUPOSPERMISOS.CONSULTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2489),
                            Nombre = "CONSULTAR GRUPOS PERMISOS",
                            ProgramaId = 14,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 26,
                            AccionId = 2,
                            Codigo = "GRUPOSPERMISOS.CREAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2491),
                            Nombre = "CREAR GRUPOS PERMISOS",
                            ProgramaId = 14,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 27,
                            AccionId = 3,
                            Codigo = "GRUPOSPERMISOS.MODIFICAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2493),
                            Nombre = "MODIFICAR GRUPOS PERMISOS",
                            ProgramaId = 14,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 28,
                            AccionId = 4,
                            Codigo = "GRUPOSPERMISOS.ELIMINAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2494),
                            Nombre = "ELIMINAR GRUPOS PERMISOS",
                            ProgramaId = 14,
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 29,
                            AccionId = 5,
                            Codigo = "GRUPOSPERMISOS.LISTAR",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2496),
                            Nombre = "LISTAR GRUPOS PERMISOS",
                            ProgramaId = 14,
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.ToTable("SEG_Programas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "GRUPOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2360),
                            Nombre = "MAESTRO DE GRUPOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "CONTRARREFERENCIA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2362),
                            Nombre = "CONTRARREFERENCIA A PACIENTES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "MEDICOSSEDES",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2363),
                            Nombre = "MEDICOS POR SEDE",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "REFERENCIA",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2366),
                            Nombre = "REFERENCIA A PACIENTES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "EMPRESAS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2368),
                            Nombre = "EMPRESAS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "SEDES",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2370),
                            Nombre = "SEDES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "LISTAS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2372),
                            Nombre = "MAESTRO DE LISTAS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "DATOSCONSTANTES",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2373),
                            Nombre = "MAESTRO DE DATOS CONSTANTES",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "USUARIOSSEDESGRUPOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2375),
                            Nombre = "ASOCIACION DE USUARIOS SEDES GRUPOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "PROGRAMAS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2377),
                            Nombre = "MAESTRO DE PROGRAMAS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "USUARIOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2380),
                            Nombre = "MAESTRO DE USUARIOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "ACCIONES",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2382),
                            Nombre = "ACCIONES EN PROGRAMAS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "PERMISOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2384),
                            Nombre = "PERMISOS",
                            UsuarioCreadorId = 1
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "GRUPOSPERMISOS",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2385),
                            Nombre = "PERMISOS DE GRUPOS",
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Apellido2")
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("CambiarClave")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GrupoDirectoId")
                        .HasColumnType("int")
                        .HasComment("ID del grupo que tiene directamente el usuario, es decir, no depende de la empresa");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre2")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GrupoDirectoId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.HasIndex("TipoIdentificacionId", "Identificacion")
                        .IsUnique();

                    b.ToTable("SEG_Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido1 = "SISTEMA",
                            Apellido2 = "",
                            CambiarClave = true,
                            Clave = "1feTCdMwhKKkOSWaM5+yXEI0ZrBPlq9pbnB4k4+JRUU=",
                            Email = "CORREO@GMAIL.COM",
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2084),
                            Identificacion = "ADMINISTRADOR",
                            Nombre1 = "ADMINISTRADOR",
                            Nombre2 = "",
                            NombreUsuario = "ADMINISTRADOR",
                            TipoIdentificacionId = 1,
                            UsuarioCreadorId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_UsuarioSedeGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioCreadorId");

                    b.HasIndex("UsuarioModificadorId");

                    b.HasIndex("UsuarioId", "SedeId")
                        .IsUnique();

                    b.ToTable("SEG_UsuariosSedesGrupos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoActivo = true,
                            FechaCreado = new DateTime(2026, 7, 19, 14, 22, 46, 458, DateTimeKind.Local).AddTicks(2596),
                            GrupoId = 1,
                            SedeId = 1,
                            UsuarioCreadorId = 1,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Accion", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Grupo", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_GrupoPermiso", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Grupo", "Grupo")
                        .WithMany("GruposPermisos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Permiso", "Permiso")
                        .WithMany("GruposPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("Permiso");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Permiso", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Accion", "Accion")
                        .WithMany("Permisos")
                        .HasForeignKey("AccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Programa", "Programa")
                        .WithMany("Permisos")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId");

                    b.Navigation("Accion");

                    b.Navigation("Programa");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Programa", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Usuario", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Grupo", "Grupo")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoDirectoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_UsuarioSedeGrupo", b =>
                {
                    b.HasOne("SEG.Dominio.Entidades.SEG_Grupo", "Grupo")
                        .WithMany("UsuariosSedes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "Usuario")
                        .WithMany("UsuariosSedes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SEG.Dominio.Entidades.SEG_Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioCreador");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Accion", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Grupo", b =>
                {
                    b.Navigation("GruposPermisos");

                    b.Navigation("Usuarios");

                    b.Navigation("UsuariosSedes");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Permiso", b =>
                {
                    b.Navigation("GruposPermisos");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Programa", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("SEG.Dominio.Entidades.SEG_Usuario", b =>
                {
                    b.Navigation("UsuariosSedes");
                });
#pragma warning restore 612, 618
        }
    }
}
